#!/usr/bin/env bash

set -e

container_name=${PROJECT_NAME}-${BUILD_VERSION}-%i

cat <<EOF
[Unit]
Description=${PROJECT_NAME}

[Service]
User=core
Type=simple
Restart=on-failure

ExecStartPre=/usr/bin/docker pull ${PRIVATE_DOCKER_REGISTRY}/${PROJECT_NAME}:${BUILD_VERSION}
ExecStartPre=/usr/bin/bash -c ' \
  for id in \$(docker ps --all --quiet --filter name=${PROJECT_NAME}-${BUILD_VERSION}-*); do \
    docker rm --force \$id; \
  done; \
  '

ExecStart=/usr/bin/docker run --rm \
  --read-only \
  --name ${container_name} \
  --env UNIT_NAME=%n \
  --publish  8090:8080 \
  ${PRIVATE_DOCKER_REGISTRY}/${PROJECT_NAME}:${BUILD_VERSION}

ExecStop=/usr/bin/docker stop ${container_name}

[X-Fleet]
Conflicts=${PROJECT_NAME}-${BUILD_VERSION}@*.service
EOF
